### ISSUE TITLE
Aaron to draft email to CSM about intro to learn more about their data

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#39]

**Comment by aaronhaefner** [comment]
Posting for feedback

Subject: Connecting about development of new arrivals platform

Hi Dan and Saara,

Since our conversation, we have been refining our ideas for the platform we are developing for new arrivals in Chicago.

Your feedback has been very useful, particularly the insight regarding the lack of feasibility of providing live nearby clinic scheduling and availability, and has helped guide our design decisions. We are also interested in learning more about the data being collected by the student group you mentioned to better understand the informational landscape we are working in.

Would you be willing to connect us with them? We believe their insights could greatly inform our decisions on what information to display about organizations and clinics, such as translator availability, and assist in verifying our own English-Spanish translations of health information for our platform.

Thank you, and please let us know if there is any additional information we can provide.

Best,
Aaron

**Comment by klinkoberstar** [comment]
my only comment would be that I think you could start the new paragraph at "We are also interested..."  instead of the previous line  (since it's the start of a new ask/idea)

I think it's good! i like that you acknowledge some specific parts of their feedback that we've incorporated in our planning

**Comment by aaronhaefner** [comment]
Great thank you. Sent - I think we can close this issue and spin up a new issue regarding any next steps?
