### ISSUE TITLE
Extend base HTML to legal page

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#71]

**Comment by sumslong** [comment]
Can someone clarify this issue? re: what I said in the chat

The formatting on home.html and legal.html are a bit different with little overlap which is why I opted to not go with the "extends" method

If we like the font, we could just do extends with the font and some smaller things -- and make a base.html file for that, but I'm not sure having legal.html extending from home.html makes sense without extensive blocking in home.html

**Comment by klinkoberstar** [comment]
> Can someone clarify this issue? re: what I said in the chat
> 
> The formatting on home.html and legal.html are a bit different with little overlap which is why I opted to not go with the "extends" method
> 
> If we like the font, we could just do extends with the font and some smaller things -- and make a base.html file for that, but I'm not sure having legal.html extending from home.html makes sense without extensive blocking in home.html

@MadeleineKRoberts want to make sure you see this since you requested this issue!

**Comment by sumslong** [comment]
Also, to add on: I reviewed PR #69 and left a comment re: this, but the current implementation incorporating the base.html and extending to home.html has lost some of the mobile responsiveness that we are trying to prioritize. I think this is because the pages are formatted so differently. So, base.html needs to be modified (either by me or Maddie) before it can be extended to legal.html.

**Comment by sumslong** [comment]
did not automatically close but resolved by PR #86
